### ISSUE TITLE
inactive include (i.e., missing `[+]` button)

### ISSUE THREAD

**Issue by pw374** [ocamllabs/opam-doc#29] opened 2013-09-19 23:18 UTC
e.g., http://ocaml-redesign.github.io/docs/opam/?package=core&module=Bool

**Comment by lpw25** [comment] 2013-09-19 23:23
I think these may be being caused by opamdoc running on some files before their dependencies. The easiest way to fix this is probably to run opamdoc over all the cmd/cmt files twice: the first time to make sure that all the files are present in the index and the second time to actually generate the html files.

**Comment by pw374** [comment] 2013-09-19 23:35
I don't quite understand how to run opamdoc twice.

In Anil's script ([`opamdoc-generate`](https://github.com/ocamllabs/opam-doc/issues/1#issuecomment-23430108)) there is

```
for pkg in ${PKGS}; do
  fs="$(find $DOC/$pkg -type f)"
  if [ "$fs" != "" ]; then
    name=$(echo $pkg | awk -F. '{print $1}')
    echo $pkg $name
    $dry $OPAMDOC -p $name $fs
  fi
done
```

and running that loop twice doesn't seem to change anything...
What am I missing?

**Comment by lpw25** [comment] 2013-09-20 00:11
Running that loop twice should do it, so the problem must be elsewhere :-(

**Comment by lpw25** [comment] 2013-09-20 01:30
This should be fixed by #32

**Comment by pw374** [comment] 2013-09-20 09:25
#32  has changed something, but not quite the right way: http://ocaml-redesign.github.io/docs/opam/?package=core&module=Bool

**Comment by pw374** [comment] 2013-09-21 00:18
One thing to note: 
[opamdoc-rebuild](https://github.com/ocamllabs/opam-doc/issues/1#issuecomment-23430108) does not copy enough files (it misses some .cmt).

**Comment by pw374** [comment] 2013-09-21 00:23
`CMDS=$(find ${pkg} -type f -name '*.cmd')` ==> search for cmd is not sufficient when cmd files don't exist while cmt do.

**Comment by pw374** [comment] 2013-09-21 15:05
http://ocaml.org.philippewang.info/pkg/docs/?package=core&module=Bool is working!! Hooray!!
Thanks Vincent.

**Closed as completed** 2013-09-21 15:36 UTC
