### ISSUE TITLE
Set of docs on http://ocaml-redesign.github.io for the RWO tutorial in Boston

### ISSUE THREAD

**Issue by amirmc** [ocamllabs/opam-doc#14] opened 2013-09-18 16:16 UTC
We need a set of working, styled, documentation up on the website for the RWO packages.  The immediate need is that a bunch of people will be using these docs on the 23rd of September (during the [tutorial at CUFP](http://cufp.org/conference/sessions/2013/t2-yaron-minsky-anil-madhavapeddy-ocaml-tutorial)).  The RWO packages are `core`, `core_bench`, `core-extended`, `async` and `utop` (and the associated dependencies).

We have to get them in shape very soon and this involves coordinating work between `opamdoc`, the website styling and (to a lesser extent) the output from `opam2web`.  We're in pretty good shape with the work we've done to so far but we need to make things far more useable.

Please do edit/add to this issue as we find and fix the bugs.

General
- [x] populate `/pkg` with unstyled opam2web output
- [x] add first pass at package docs to demo site (under `/docs/opam`)
- [ ] rebuild `/pkg` so it only has the RWO universe (easier to navigate)
- [x] merge documentation into pkg
- [x] include the standard library in the documentation

opam-doc
- [x] fix indentation
- [x] ensure linking cross-linking works (see #20)
- [x] fix browser hangs (see #22)
- [x] remove random stuff at bottom of page (cf [Core_list](http://ocaml-redesign.github.io/docs/opam/?package=core_kernel&module=Core_list))
- [ ] when a module is unfolded, the unfolded contents should be between the `sig` and `end` markers, rather than after a `sig ... end`.
- [x] remove duplicates from index pages
- [x] alphabetical order in front page

styles for docs on ocaml.org
- [x] try out unstyled docs
- [x] fix Code/pre blocks to remove gray boxes
- [x] increase default text size
- [x] apply new syntax colours
- [x] fix spacing on `<li>` text
- [x] add appropriate code blocks (cf [Utop](http://ocaml-redesign.github.io/docs/opam/?package=utop&module=UTop)). So leave the gray outline for code within `<pre class="codepre"></pre>` tags.
- [ ] fix spacing around titles
- [x] fix spacing and indentation of the info blocks so that they are clearly associated with the correct item.
- [x] restrict the width of the output so that text is word-wrapped.

**Comment by amirmc** [comment] 2013-09-18 16:30
Looping in @avsm @lpw25 and @pw374.  We have 4 days to get this done, which is achievable, given that we have a good starting point.

**Comment by avsm** [comment] 2013-09-18 16:39
The Core_list issue is due to a loss of location precision in the camlp4 layer, which is leading to shoving all the docs to the end of the page.  This looks horrendous, but the only way to figure out the issue is to bisect all the syntax packages involved in Core (which you can see listed in the `corebuild` script if you install Core).

Also: can you increase the default text font size please?

**Comment by amirmc** [comment] 2013-09-18 21:13
Already looking a _lot_ better. Thanks Philippe.

**Comment by pw374** [comment] 2013-09-19 12:23
> Already looking a _lot_ better. Thanks Philippe.

:-)

Can someone please tell me where I can find the list of packages of the RWO universe? I'm going to try and fix opamdoc today.

**Comment by amirmc** [comment] 2013-09-19 12:32
Listed in the main issue.  In a new switch, if you `opam install core core_bench core-extended async utop`, then you should get everything.

**Comment by pw374** [comment] 2013-09-19 12:32
oops!

**Comment by amirmc** [comment] 2013-09-19 12:32
see also https://github.com/ocamllabs/rwo-docs

**Comment by pw374** [comment] 2013-09-20 13:34
> merge documentation into pkg

done, now waiting for github to synchronise...
(once done, there will be a link from the old page to the new one, which is in /pkg/docs/)

**Comment by dsheets** [comment] 2013-09-20 13:55
Which packages do you want the RWO universe's index to contain? Only the top level packages? All the packages in the transitive closure? Some other set part-way between these two extremes?

**Comment by pw374** [comment] 2013-09-20 15:29
Since Github might take hours (instead of "up to 10 minutes") to update the website, I've set up a mirror: http://ocaml.org.philippewang.info

**Comment by pw374** [comment] 2013-09-22 22:54
> when a module is unfolded, the unfolded contents should be between the sig and end markers, rather than after a sig ... end.

I'd like more information about this because I don't understand it (perhaps it's been fixed?)

**Comment by pw374** [comment] 2013-09-23 00:20
> remove duplicates from index pages

I believe that I've just fixed that.  (Except for Cow's documentation: there must be something wrong with some `.cm[td]?i?` files)

**Comment by lpw25** [comment] 2013-09-23 14:36
> I'd like more information about this because I don't understand it (perhaps it's been fixed?)

This refers to the fact that a sub-module like:

``` ocaml
module M : sig ... end
```

is expanded to:

``` ocaml
module M : sig ... end
    type t 
    val x : t
```

instead of:

``` ocaml
module M : sig
    type t
    val x : t
end
```

**Comment by lpw25** [comment] 2013-11-01 15:03
The issues in this are either solved or moved into a separate issue, so I'm closing this one.

**Closed as completed by lpw25** 2013-11-01 15:03 UTC
